<?php

$cookbooks = [
    ["title" => "Salt, Fat, Acid, Heat", "author" => "Samin Nosrat", "theme" => "Cooking fundamentals"],
    ["title" => "The Food Lab", "author" => "J. Kenji López-Alt", "theme" => "Science-based cooking"],
    ["title" => "Joy of Cooking", "author" => "Irma S. Rombauer", "theme" => "Classic American cooking"],
    ["title" => "Essentials of Classic Italian Cooking", "author" => "Marcella Hazan", "theme" => "Italian"],
    ["title" => "Japan: The Cookbook", "author" => "Nancy Singleton Hachisu", "theme" => "Japanese"],
    ["title" => "Mexican Everyday", "author" => "Rick Bayless", "theme" => "Mexican"],
    ["title" => "The Nordic Cookbook", "author" => "Magnus Nilsson", "theme" => "Nordic cuisine"],
    ["title" => "Dishoom: From Bombay with Love", "author" => "Shamil Thakrar", "theme" => "Indian"],
    ["title" => "Oaxaca: Home Cooking from the Heart of Mexico", "author" => "Bricia Lopez", "theme" => "Regional Mexican"],
    ["title" => "Vegetable Kingdom", "author" => "Bryant Terry", "theme" => "Plant-based cooking"],
    ["title" => "Mastering the Art of French Cooking", "author" => "Julia Child", "theme" => "French"],
    ["title" => "Indian-ish", "author" => "Priya Krishna", "theme" => "Modern Indian"],
    ["title" => "Korean Home Cooking", "author" => "Sohui Kim", "theme" => "Korean"],
    ["title" => "The Wok: Recipes and Techniques", "author" => "J. Kenji López-Alt", "theme" => "Asian stir-fry"],
    ["title" => "Noma: Time and Place in Nordic Cuisine", "author" => "René Redzepi", "theme" => "Nordic fine dining"],
    ["title" => "The Palestinian Table", "author" => "Reem Kassis", "theme" => "Middle Eastern"],
    ["title" => "Simply Julia", "author" => "Julia Turshen", "theme" => "Healthy home cooking"],
    ["title" => "Falastin", "author" => "Sami Tamimi", "theme" => "Palestinian cuisine"],
    ["title" => "Aloha Kitchen", "author" => "Alana Kysar", "theme" => "Hawaiian"],
    ["title" => "Tartine Bread", "author" => "Chad Robertson", "theme" => "Bread baking"],
    ["title" => "The New Vegetarian Cooking for Everyone", "author" => "Deborah Madison", "theme" => "Vegetarian"],
    ["title" => "Baking with Dorie", "author" => "Dorie Greenspan", "theme" => "Baking"],
    ["title" => "Sweet", "author" => "Yotam Ottolenghi", "theme" => "Desserts"],
    ["title" => "Bread Illustrated", "author" => "America's Test Kitchen", "theme" => "Bread baking"],
    ["title" => "The Whole Fish Cookbook", "author" => "Josh Niland", "theme" => "Sustainable seafood"],
    ["title" => "Six Seasons: A New Way with Vegetables", "author" => "Joshua McFadden", "theme" => "Vegetable-focused"],
    ["title" => "Bao", "author" => "Eddie Huang", "theme" => "Taiwanese street food"],
    ["title" => "Pok Pok", "author" => "Andy Ricker", "theme" => "Thai cuisine"],
    ["title" => "Gullah Geechee Home Cooking", "author" => "Emily Meggett", "theme" => "Southern cuisine"],
    ["title" => "Burmese Cooking", "author" => "MiMi Aye", "theme" => "Burmese"],
    ["title" => "Chicano Eats", "author" => "Esteban Castillo", "theme" => "Mexican-American"],
    ["title" => "The Arabesque Table", "author" => "Reem Kassis", "theme" => "Middle Eastern"],
    ["title" => "La Grotta", "author" => "Kitty Travers", "theme" => "Ice cream and gelato"],
    ["title" => "Moro: The Cookbook", "author" => "Samuel Clark", "theme" => "Spanish & Moorish"],
    ["title" => "The Pho Cookbook", "author" => "Andrea Nguyen", "theme" => "Vietnamese"],
    ["title" => "My Mexico City Kitchen", "author" => "Gabriela Cámara", "theme" => "Mexican"],
    ["title" => "The Sichuan Cookbook", "author" => "Fuchsia Dunlop", "theme" => "Chinese - Sichuan"],
    ["title" => "Tasting Georgia", "author" => "Carla Capalbo", "theme" => "Georgian"],
    ["title" => "Arabian Nights Cookbook", "author" => "Habeeb Salloum", "theme" => "Middle Eastern"],
    ["title" => "Jikoni", "author" => "Ravinder Bhogal", "theme" => "Fusion - Indian & British"]
];
